routeHost: 'timetable-field-number-frontend-test.apps.aws01t.sbb-aws-test.net'
environmentLabel: 'test'
backendUrl: 'https://timetable-field-number-backend-test.apps.aws01t.sbb-aws-test.net'
splunkIndex: 'sbb_applications_internal_test_events'
