/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateRange } from './dateRange';


export interface AccessibilityRow { 
    dateRange?: DateRange;
    accessibilityState?: AccessibilityRow.AccessibilityStateEnum;
}
export namespace AccessibilityRow {
    export type AccessibilityStateEnum = 'AUTONOMY' | 'RAMP_USE' | 'PRE_REGISTRATION' | 'NO_ACCESS' | 'NO_INFO' | 'SHUTTLE';
    export const AccessibilityStateEnum = {
        Autonomy: 'AUTONOMY' as AccessibilityStateEnum,
        RampUse: 'RAMP_USE' as AccessibilityStateEnum,
        PreRegistration: 'PRE_REGISTRATION' as AccessibilityStateEnum,
        NoAccess: 'NO_ACCESS' as AccessibilityStateEnum,
        NoInfo: 'NO_INFO' as AccessibilityStateEnum,
        Shuttle: 'SHUTTLE' as AccessibilityStateEnum
    };
}


