/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BulkImportLogEntry } from './bulkImportLogEntry';
import { ServicePointGlobalIdUpdateCsvModel } from './servicePointGlobalIdUpdateCsvModel';


export interface BulkImportUpdateContainerServicePointGlobalIdUpdateCsvModel { 
    bulkImportId?: number;
    lineNumber?: number;
    object?: ServicePointGlobalIdUpdateCsvModel;
    attributesToNull?: Array<string>;
    inNameOf?: string;
    bulkImportLogEntry?: BulkImportLogEntry;
}

