/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Language = 'DE' | 'FR' | 'IT';

export const Language = {

    De: 'DE' as Language,

    Fr: 'FR' as Language,

    It: 'IT' as Language
};

