/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type LevelAccessWheelchairAttributeType = 'TO_BE_COMPLETED' | 'YES' | 'YES_WITH_STAFF_ASSISTANCE' | 'NO' | 'NOT_APPLICABLE';

export const LevelAccessWheelchairAttributeType = {

    ToBeCompleted: 'TO_BE_COMPLETED' as LevelAccessWheelchairAttributeType,

    Yes: 'YES' as LevelAccessWheelchairAttributeType,

    YesWithStaffAssistance: 'YES_WITH_STAFF_ASSISTANCE' as LevelAccessWheelchairAttributeType,

    No: 'NO' as LevelAccessWheelchairAttributeType,

    NotApplicable: 'NOT_APPLICABLE' as LevelAccessWheelchairAttributeType
};

