/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ManualMail { 
    /**
     * Manually maintained E-Mail address. An empty/blank value removes the override so the Azure E-Mail address applies again.
     */
    mail?: string;
}

