/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OtpResponse { 
    /**
     * True if a new one-time code was generated and sent by mail. False if the previously sent one-time code is still valid and therefore has to be reused
     */
    mailSent?: boolean;
    /**
     * Seconds until the currently valid one-time code expires. A new one-time code can only be obtained after this period
     */
    expiresInSeconds?: number;
}

