/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BooleanOptionalAttributeType } from './booleanOptionalAttributeType';
import { BasicAttributeType } from './basicAttributeType';
import { LevelAccessWheelchairAttributeType } from './levelAccessWheelchairAttributeType';
import { BoardingDeviceAttributeType } from './boardingDeviceAttributeType';


export interface PlatformCompleteUpdateCsvModel { 
    sloid?: string;
    validFrom?: Date;
    validTo?: Date;
    boardingDevice?: BoardingDeviceAttributeType;
    additionalInformation?: string;
    shuttle?: BooleanOptionalAttributeType;
    adviceAccessInfo?: string;
    contrastingAreas?: BooleanOptionalAttributeType;
    dynamicAudio?: BasicAttributeType;
    dynamicVisual?: BasicAttributeType;
    inclination?: number;
    inclinationWidth?: number;
    levelAccessWheelchair?: LevelAccessWheelchairAttributeType;
    superelevation?: number;
}
export namespace PlatformCompleteUpdateCsvModel {
}


