/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SectorGroupCreateCsvModel { 
    trafficPointSloid?: string;
    validFrom?: Date;
    validTo?: Date;
    designation?: string;
    length?: number;
    sectorSloids?: Set<string>;
}

