/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SublineConcessionType } from './sublineConcessionType';


export interface SublineUpdateCsvModel { 
    slnid?: string;
    linienId?: string;
    validFrom?: Date;
    validTo?: Date;
    description?: string;
    swissSublineNumber?: string;
    sublineConcessionType?: SublineConcessionType;
    longName?: string;
    businessOrganisation?: string;
}
export namespace SublineUpdateCsvModel {
}


