/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatementStatus } from './statementStatus';


export interface TimetableHearingAnonymStatementCsvModel { 
    timetableHearingStatementId?: number;
    cantonAbbreviation?: string;
    status?: StatementStatus;
    timetableFieldNumber?: string;
    timetableFieldNumberDescription?: string;
    stopPlace?: string;
    transportCompanyAbbreviations?: string;
    transportCompanyDescriptions?: string;
    statement?: string;
    documentsPresent?: boolean;
    timetableHearingYear?: number;
    topic?: string;
}
export namespace TimetableHearingAnonymStatementCsvModel {
}


