/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserAccountStatus } from './userAccountStatus';
import { Permission } from './permission';


export interface User { 
    /**
     * SBB User Id
     */
    sbbUserId: string;
    /**
     * User lastname
     */
    lastName?: string;
    /**
     * User firstname
     */
    firstName?: string;
    /**
     * Effective E-Mail address: the manually maintained override if one is set, otherwise the original address from the source system.
     */
    mail?: string;
    /**
     * Original, unmodified E-Mail address from the source system. Differs from mail exactly when a manual override is currently active.
     */
    originalMail?: string;
    /**
     * User display name (azure)
     */
    displayName?: string;
    accountStatus?: UserAccountStatus;
    /**
     * User permissions
     */
    permissions: Set<Permission>;
    userId?: string;
}
export namespace User {
}


