/**
 * Atlas API
 *
 * Contact: TechSupport-ATLAS@sbb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type WheelchairAccessibilityState = 'AUTONOMY' | 'RAMP_USE' | 'PRE_REGISTRATION' | 'NO_ACCESS' | 'NO_INFO' | 'SHUTTLE';

export const WheelchairAccessibilityState = {

    Autonomy: 'AUTONOMY' as WheelchairAccessibilityState,

    RampUse: 'RAMP_USE' as WheelchairAccessibilityState,

    PreRegistration: 'PRE_REGISTRATION' as WheelchairAccessibilityState,

    NoAccess: 'NO_ACCESS' as WheelchairAccessibilityState,

    NoInfo: 'NO_INFO' as WheelchairAccessibilityState,

    Shuttle: 'SHUTTLE' as WheelchairAccessibilityState
};

