spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true
      properties:
        spring:
          json:
            trusted:
              packages: "*"
        max:
          poll:
            interval:
              ms: 1200000
    producer:
      properties:
        max:
          request:
            size: 3000000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 1

---

spring:
  profiles: dev
  kafka:
    bootstrap-servers: test01.kafka.sbb.ch:9095

---

spring:
  profiles: test
  kafka:
    bootstrap-servers: test01.kafka.sbb.ch:9095

---

spring:
  profiles: int
  kafka:
    bootstrap-servers: inte01.kafka.sbb.ch:9095

---

spring:
  profiles: prod
  kafka:
    bootstrap-servers: prod01.kafka.sbb.ch:9095