repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.36.0
    hooks:
      - id: ggshield
        name: checking for secrets
        language_version: python3
        args: ["-c", "ggshield.yaml", "secret", "scan", "pre-commit", "--all-secrets"]
