version: "3.8"

services:
  lidi-db:
    image: postgres:14.2
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: line-directory
    volumes:
      - "/var/lib/postgresql/data"
    command:
      - "postgres"
      - "-c"
      - "datestyle=iso, ymd"

  bodi-db:
    image: postgres:14.2
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: business-organisation-directory
    volumes:
      - "/var/lib/postgresql/data"
    command:
      - "postgres"
      - "-c"
      - "datestyle=iso, ymd"

  scheduling-db:
    image: postgres:14.2
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: scheduling
    volumes:
      - "/var/lib/postgresql/data"
    command:
      - "postgres"
      - "-c"
      - "datestyle=iso, ymd"

  user-administration-db:
    image: postgres:14.2
    restart: always
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: user-administration
    volumes:
      - "/var/lib/postgresql/data"
    command:
      - "postgres"
      - "-c"
      - "datestyle=iso, ymd"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      # atlas.mail will have 1 partition and 1 replicas
      KAFKA_CREATE_TOPICS: "atlas.mail:1:1, atlas.user.administration:1:1"
