version: "3.8"

services:
  postgres:
    image: postgres:13.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: line-directory
    volumes:
      - "/var/lib/postgresql/data"
    command:
      - "postgres"
      - "-c"
      - "datestyle=iso, ymd"