spring:
  datasource:
    url: TBD
    username: ${DB_USER}
    password: ${DB_PWD}
auth:
  audience:
    service-name: f3cdcb3e-1e95-4591-b664-4526d00f5d66
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n