spring:
  datasource:
    url: jdbc:postgresql://scheduling-int.cdv0rjtmldns.eu-central-1.rds.amazonaws.com:5432/scheduling
    username: ${DB_USER}
    password: ${DB_PWD}
  kafka:
    atlas:
      mail:
        topic: atlas.int.mail
        groupId: atlas.kafka.user
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/v2.0
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/v2.0
        registration:
          azure:
            authorization-grant-type: client_credentials
            client-id: ${SCHEDULING_CLIENT_ID}
            client-secret: ${SCHEDULING_CLIENT_SECRET}
            scope:
              - api://733b361e-a067-4882-bb00-6bbaf36a007f/.default
auth:
  audience:
    service-name: 733b361e-a067-4882-bb00-6bbaf36a007f
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n
atlas:
  client:
    gateway:
      url: "http://gateway:8888"