spring:
  datasource:
    url: jdbc:postgresql://timetable-field-number-int.cdv0rjtmldns.eu-central-1.rds.amazonaws.com:5432/timetable_field_number
    username: ${DB_USER}
    password: ${DB_PWD}
auth:
  audience:
    service-name: 733b361e-a067-4882-bb00-6bbaf36a007f
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{X-B3-TraceId:-} spanid=%X{X-B3-SpanId:-} message="%m"%n