spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/timetable-field-number
    username: user
    password: pwd
    driver-class-name: org.postgresql.Driver
  security:
    user:
      password: pwd
management:
  endpoints:
    web:
      exposure:
        include: "*"