spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/timetable-field-number
    username: user
    password: pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/v2.0
auth:
  audience:
    service-name: 87e6e634-6ba1-4e7a-869d-3348b4c3eafc
server:
  port: 8080
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: timetable-field-number-backend
    version: @version@
    buildtime: @timestamp@
logging:
  level:
    root: INFO
    org.hibernate: ERROR
