spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/line-directory
    username: user
    password: pwd
    driver-class-name: org.postgresql.Driver
  security:
    user:
      password: pwd
  jpa:
    open-in-view: false
server:
  port: 8081
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: line-directory-backend
    version: @version@
    buildtime: @timestamp@
endpoints:
  web:
    cors:
      path-mappings: /**
      allowed-origins: http://localhost:4200,https://developer-int.sbb.ch,https://developer.sbb.ch
      allowed-methods: GET,PUT,POST,DELETE
      allowed-headers: "*"
logging:
  level:
    root: INFO
    org.hibernate: ERROR
