logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{X-B3-TraceId:-} spanid=%X{X-B3-SpanId:-} message="%m"%n
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: https://atlas.sbb-cloud.net,https://atlas.app.sbb.ch,https://developer.sbb.ch
gateway:
  routes:
    line-directory: http://line-directory-backend:8082
