spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/timetable-field-number
    username: user
    password: pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/v2.0
auth:
  audience:
    service-name: fa0c4e69-d22b-47ff-b71d-af9493919cc6
server:
  port: 8080
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: timetable-field-number-backend
    version: @version@
    buildtime: @timestamp@
endpoints:
  web:
    cors:
      path-mappings: /**
      allowed-origins: http://localhost:4200,https://developer-int.sbb.ch,https://developer.sbb.ch
      allowed-methods: GET,PUT,POST,DELETE
      allowed-headers: "*"
logging:
  level:
    root: INFO
    org.hibernate: ERROR
