spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/business-organisation-directory?currentSchema=business_organisation_directory
    username: user
    password: pwd
    driver-class-name: org.postgresql.Driver
  application:
    name: business-organisation-directory
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 500
  jmx:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/v2.0
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true
      properties:
        spring:
          json:
            trusted:
              packages: "*"
        max:
          poll:
            interval:
              ms: 1200000
    producer:
      properties:
        max:
          request:
            size: 3000000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 1

kafka:
  atlas:
    mail:
      topic: atlas.mail
      groupId: atlas.kafka.mail.groupId
    user:
      administration:
        topic: atlas.user.administration
        groupId: atlas.kafka.bodi.user.administration.groupId
    business:
      organisation:
        topic: atlas.business.organisation
        groupId: atlas.kafka.bodi.business.organisation.groupId
    transport:
      company:
        topic: atlas.transport.company
        groupId: atlas.kafka.bodi.transport.company.groupId
auth:
  audience:
    service-name: 87e6e634-6ba1-4e7a-869d-3348b4c3eafc
server:
  port: 8083
  error:
    include-message: always
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics
info:
  app:
    name: business-organisation-directory
    version: 1.0.0
    buildtime: ${time}

logging:
  level:
    root: INFO
    org.hibernate: ERROR
external:
  bav:
    url: https://www.output.tu-verzeichnisse.bav.admin.ch
mail:
  receiver:
    tu-relations-report: TechSupport-ATLAS@sbb.ch
amazon:
  region: local
  bucketConfigs:
    bulk-import:
      accessKey: NSVCQSGo2klxYXInNuob
      secretKey: jiiCYSlwdHBkrSg8J4Htqm7Ej8ydlprZGgYFwELc
      endpoint: "http://localhost:9000"
      forcePathStyle: true
      objectExpirationDays:
