spring:
  datasource:
    url: jdbc:postgresql://business-organisation-directory-dev.cdv0rjtmldns.eu-central-1.rds.amazonaws.com:5432/business_organisation_directory
    username: ${DB_USER}
    password: ${DB_PWD}
  kafka:
    bootstrap-servers: test01.kafka.sbb.ch:9095
    ssl:
      trust-store-location: ${KAFKA_TRUSTSTORE_LOCATION}
      trust-store-password: ${KAFKA_TRUSTSTORE_PASSWORD}
      trust-store-type: PKCS12
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-512
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="atlas.kafka.user" password="${KAFKA_SCRAM_PASSWORD}";
    atlas:
      mail:
        topic: atlas.dev.mail
        groupId: atlas.kafka.user
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n