spring:
  datasource:
    url: jdbc:postgresql://business-organisation-directory-prod.czdfgxj0x1zx.eu-central-1.rds.amazonaws.com:5432/business_organisation_directory
    username: ${DB_USER}
    password: ${DB_PWD}
  kafka:
    atlas:
      mail:
        topic: atlas.prod.mail
        groupId: atlas.kafka.user
      user:
        administration:
          topic: atlas.prod.user.administration
          groupId: atlas.kafka.user
auth:
  audience:
    service-name: f3cdcb3e-1e95-4591-b664-4526d00f5d66
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n
mail:
  receiver:
    tu-relations-report: atlas@sbb.ch
amazon:
  accessKey: ${AMAZON_S3_ACCESS_KEY}
  secretKey: ${AMAZON_S3_SECRET_KEY}
  region: "eu-central-1"
  bucketName: "atlas-data-export-prod"
  objectExpirationDays: 30