spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/business-organisation-directory
    username: user
    password: pwd
    driver-class-name: org.postgresql.Driver
  application:
    name: business-organisation-directory
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 500
  jmx:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/v2.0
auth:
  audience:
    service-name: 87e6e634-6ba1-4e7a-869d-3348b4c3eafc
server:
  port: 8083
  error:
    include-message: always
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: business-organisation-directory
    version: @version@
    buildtime: @timestamp@
logging:
  level:
    root: INFO
    org.hibernate: ERROR
external:
  mail:
    url: http://localhost:8084
  bav:
    url: https://www.output.tu-verzeichnisse.bav.admin.ch
    # Environment Variables used for CRD can be found in the restricted access page for passwords
  crd:
    url: https://crd.rne.eu/CRD/services/CRDRFDataReplicationWS
    username: fs10651_li
    password: ${CRD_PASSWORD}
    keystore: classpath:crd/keystore.jks
    keystore-password: ${CRD_KEYSTORE_PASSWORD}
    keystore-alias: atlas
    truststore: classpath:crd/rne-truststore.jks
    truststore-password: ${CRD_TRUSTSTORE_PASSWORD}
mail:
  receiver:
    tu-relations-report: TechSupport-ATLAS@sbb.ch
