spring:
  datasource:
    url: replace-me
    username: ${DB_USER}
    password: ${DB_PWD}
auth:
  audience:
    service-name: replace-me
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n
external:
  url:
    bav: https://www.output.tu-verzeichnisse.bav.admin.ch