spring:
  datasource:
    url: jdbc:postgresql://business-organisation-directory-dev.cdv0rjtmldns.eu-central-1.rds.amazonaws.com:5432/business_organisation_directory
    username: ${DB_USER}
    password: ${DB_PWD}
kafka:
  atlas:
    mail:
      topic: atlas.dev.mail
      groupId: atlas.kafka.mail.groupId
    user:
      administration:
        topic: atlas.dev.user.administration
        groupId: atlas.kafka.user.administration.groupId
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n