kind: Deployment
apiVersion: apps/v1
metadata:
  name: '{{ .Values.product }}{{ .Values.global.seperator }}{{ .Values.global.variant }}'
spec:
  replicas: {{ .Values.global.replicas }}
  selector:
    matchLabels:
      app: '{{ .Values.product }}{{ .Values.global.seperator }}{{ .Values.global.variant }}'
      deploymentconfig: '{{ .Values.product }}{{ .Values.global.seperator }}{{ .Values.global.variant }}'
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        collectord.io/logs-index: '{{ .Values.global.splunkIndex }}'
        collectord.io/logs-output: splunk::prod
        collectord.io/logs-eventpattern: ^(timestamp=)
      labels:
        app: '{{ .Values.product }}{{ .Values.global.seperator }}{{ .Values.global.variant }}'
        deploymentconfig: '{{ .Values.product }}{{ .Values.global.seperator }}{{ .Values.global.variant }}'
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: '{{ .Values.global.springProfilesActive }}'
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret-{{ .Values.product }}
              key: user
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: db-secret-{{ .Values.product }}
              key: password
        image: "atlas.docker.bin.sbb.ch/{{ .Values.imageName }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: '{{ .Values.global.imagePullPolicy }}'
        name: '{{ .Values.product }}{{ .Values.global.seperator }}{{ .Values.global.variant }}'
        ports:
        - containerPort: {{ .Values.port }}
          protocol: TCP
        resources:
          requests:
            cpu: '{{ .Values.global.cpuMin }}'
            memory: '{{ .Values.global.memoryMin }}'
          limits:
            cpu: '{{ .Values.global.cpuMax }}'
            memory: '{{ .Values.global.memoryMax }}'
        livenessProbe:
          httpGet:
            path: '{{ .Values.livenessProbe }}'
            port: {{ .Values.port }}
            scheme: HTTP
          initialDelaySeconds: 40
          timeoutSeconds: 90
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: '{{ .Values.readynessProbe }}'
            port: {{ .Values.port }}
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 90
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 10
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
