logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: https://atlas.test.sbb-cloud.net,https://atlas.test.app.sbb.ch,https://developer-int.sbb.ch
gateway:
  routes:
    line-directory: http://line-directory:8082
    business-organisation-directory: http://business-organisation-directory:8083