logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: https://atlas.sbb-cloud.net,https://atlas.app.sbb.ch,https://developer.sbb.ch
gateway:
  routes:
    line-directory: http://line-directory:8082
    business-organisation-directory: http://business-organisation-directory:8083
    user-administration: http://user-administration:8086
    workflow: http://workflow:8087
    service-point-directory: http://service-point-directory:8088
