server:
  port: 8888
spring:
  sleuth:
    baggage:
      remote-fields: Correlation-Id
      correlation-fields: Correlation-Id
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: http://localhost:4200,https://developer-int.sbb.ch
            allowed-methods: GET,PUT,POST,DELETE
            allowed-headers: "*"
            exposed-headers:
              - "Correlation-Id"
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics
info:
  app:
    name: gateway
    version: @version@
    buildtime: @timestamp@
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: DEBUG
gateway:
  routes:
    line-directory: http://localhost:8082
    business-organisation-directory: http://localhost:8083
    user-administration: http://localhost:8086
