logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: http://localhost:4200,https://atlas.dev.sbb-cloud.net,https://atlas.dev.app.sbb.ch,https://developer-int.sbb.ch
gateway:
  routes:
    line-directory: http://localhost:8082
    business-organisation-directory: http://localhost:8083