server:
  port: 8084
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: mail
  sleuth:
    baggage:
      remote-fields: Correlation-Id
      correlation-fields: Correlation-Id
  mail:
    host: smtp-app.sbb.ch
    port: 587
    username: fxatl_a
    password: ${FXATL_A_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
kafka:
  atlas:
    mail:
      topic: atlas.mail
      groupId: atlas.kafka.mail.groupId