spring:
  mail:
    host: smtp-app.sbb.ch
    port: 25
    properties:
      mail:
        smtp:
          auth: false
        starttls:
          enable: false
  kafka:
    atlas:
      mail:
        topic: atlas.prod.mail
        groupId: atlas.kafka.user