auth:
  audience:
    service-name: 2e8c6ce0-304d-42e1-9bce-600b3ea43aad
azure-config:
  azure-ad-secret: ${AZURE_AD_SECRET}
  app-registration-id: 2e8c6ce0-304d-42e1-9bce-600b3ea43aad

spring:
  datasource:
    url: jdbc:postgresql://user-administration-test.cdv0rjtmldns.eu-central-1.rds.amazonaws.com/user_administration
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver
  kafka:
    atlas:
      user:
        administration:
          topic: atlas.test.user.administration
          groupId: atlas.kafka.user
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n