azure-config:
  tenant-id: 2cda5d11-f0ac-46b3-967d-af1b2e1bd01a
  azure-ad-secret: ${AZURE_AD_SECRET}
  app-registration-id: 87e6e634-6ba1-4e7a-869d-3348b4c3eafc
server:
  port: 8086
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/user-administration?currentSchema=user-administration
    username: user
    password: pwd
    driver-class-name: org.postgresql.Driver
  application:
    name: user-administration
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/v2.0
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true
      properties:
        spring:
          json:
            trusted:
              packages: "*"
        max:
          poll:
            interval:
              ms: 1200000
    producer:
      properties:
        max:
          request:
            size: 3000000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 1

kafka:
  atlas:
    user:
      administration:
        topic: atlas.user.administration
        groupId: atlas.kafka.user.administration.groupId
auth:
  audience:
    service-name: 87e6e634-6ba1-4e7a-869d-3348b4c3eafc

info:
  app:
    name: user-administration
    version: 1.0.0
    buildtime: ${time}
logging:
  level:
    root: INFO
    com:
      azure:
        identity: WARN

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics
