azure-config:
  client-secret: ${CLIENT_SECRET}
  tenant-id: 2cda5d11-f0ac-46b3-967d-af1b2e1bd01a
  client-id: 87e6e634-6ba1-4e7a-869d-3348b4c3eafc
server:
  port: 8084
  error:
    include-message: always

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/v2.0

auth:
  audience:
    service-name: 87e6e634-6ba1-4e7a-869d-3348b4c3eafc

info:
  app:
    name: user-administration
    version: @version@
    buildtime: @timestamp@
logging:
  level:
    root: INFO

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
