auth:
  audience:
    service-name: f3cdcb3e-1e95-4591-b664-4526d00f5d66
azure-config:
  azure-ad-secret: ${AZURE_AD_SECRET}
  app-registration-id: f3cdcb3e-1e95-4591-b664-4526d00f5d66

spring:
  datasource:
    url: jdbc:postgresql://user-administration-prod.czdfgxj0x1zx.eu-central-1.rds.amazonaws.com/user_administration
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver
kafka:
  atlas:
    user:
      administration:
        topic: atlas.prod.user.administration
        groupId: atlas.kafka.user.administration.groupId
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n
