spring:
  datasource:
    url: jdbc:postgresql://user-administration-dev.cdv0rjtmldns.eu-central-1.rds.amazonaws.com/user_administration
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver
  kafka:
    atlas:
      user:
        administration:
          topic: atlas.dev.user.administration
          groupId: atlas.kafka.user
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n