@startuml

title ServicePoint Status Decision Process - Update ServicePoint

start

partition "ServicePointStatusDecider"{
    if (CountryCode = 85) then (yes)
      if (isStopPoint) then (yes)
        if (has DesignationOfficial changed comparing with previos version
        OR is previous version status DRAFT) then (yes)
            if (is valid more than 60 days) then (yes)
                if (is located in Switzerland) then (yes)
                    :Status = DRAFT;
                    stop
                else(no)
                    :Status = VALIDATED;
                    stop
                endif
            else(no)
                :Status = VALIDATED;
                stop
            endif
        else(no)
            :Status = VALIDATED;
            stop
        endif
      else (no)
        :Status = VALIDATED;
        stop
      endif

    else (no)
      :Status = VALIDATED;
      stop
    endif
}

@enduml