spring:
  datasource:
    url:
    username: ${DB_USER}
    password: ${DB_PWD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/v2.0

kafka:
  atlas:
    mail:
      topic: atlas.workflow
      groupId: atlas.kafka.workflow.groupId
auth:
  audience:
    service-name: 733b361e-a067-4882-bb00-6bbaf36a007f
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n
