server:
  port: 8087
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
info:
  app:
    name: workflow
    version: 1.0.0
    buildtime: ${time}

spring:
  application:
    name: workflow
  datasource:
    url: jdbc:postgresql://localhost:5438/workflow
    username: user
    password: pwd
    driver-class-name: org.postgresql.Driver
    application:
      name: workflow
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
  jmx:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8666/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/v2.0
      client:
        provider:
          atlasAdmin:
            issuer-uri: http://localhost:8666/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/v2.0
        registration:
          atlasAdmin:
            authorization-grant-type: client_credentials
            client-id: ${SCHEDULING_CLIENT_ID}
            client-secret: ${SCHEDULING_CLIENT_SECRET}
            scope:
              - api://87e6e634-6ba1-4e7a-869d-3348b4c3eafc/.default
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true
      properties:
        spring:
          json:
            trusted:
              packages: "*"
        max:
          poll:
            interval:
              ms: 1200000
    producer:
      properties:
        max:
          request:
            size: 3000000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 1

kafka:
  atlas:
    mail:
      topic: atlas.mail
      groupId: atlas.kafka.mail.groupId
    user:
      administration:
        topic: atlas.user.administration
        groupId: atlas.kafka.workflow.user.administration.groupId

auth:
  audience:
    service-name: 87e6e634-6ba1-4e7a-869d-3348b4c3eafc

mail:
  workflow:
    line:
      receiver: a@b.ch
      from: no-reply@a.ch
    atlas:
      business: a@b.ch
    stop-point:
      from: no-reply@a.ch
atlas:
  client:
    gateway:
      url: "http://localhost:8888"
termination-examinant-mails:
  info-plus: "a@b.ch"
  nova: "a@b.ch"

examinants:
  specialistOffice:
    lastName: "SKI"
    firstname: "atlas"
    organisation: "SKI - Systemaufgaben Kundeninformation"
    email: "atlas@sbb.ch"
    function: "Fachstelle atlas"
  cantons:
  - abbreviation: "ZH"
    lastName: ""
    firstname: ""
    organisation: "ZVV Zürcher Verkehrsverbund"
    email: "a@b.ch"
    function: "Verkehrsplanung"
  - abbreviation: "BE"
    lastName: ""
    firstname: ""
    organisation: "Amt für öffentlichen Verkehr, Bau-, Verkehrs- und Energiedirektion"
    email: "a@b.ch"
    function: "Verkehrsplanung"
  - abbreviation: "LU"
    lastName: ""
    firstname: ""
    organisation: "Verkehrsverbund Luzern"
    email: "a@b.ch"
    function: "Verkehrsplanung"
  - abbreviation: "UR"
    lastName: ""
    firstname: ""
    organisation: "Volkswirtschaftsdirektion des Kantons Uri, Direktionssekretariat"
    email: "a@b.ch"
    function: "Verkehrsplanung"
  - abbreviation: "SZ"
    lastName: ""
    firstname: ""
    organisation: "Baudepartement des Kantons Schwyz, Amt für öffentlichen Verkehr"
    email: "a@b.ch"
    function: "Verkehrsplanung"
  - abbreviation: "OW"
    lastName: ""
    firstname: ""
    organisation: "Volkswirtschaftsdepartement des Kantons Obwalden, Volkswirtschaftsamt"
    email: "a@b.ch"
    function: "Fachverantwortlicher öffentlicher Verkehr"
  - abbreviation: "NW"
    lastName: ""
    firstname: ""
    organisation: "Baudirektion  Kanton Nidwalden Amt für Mobilität"
    email: "a@b.ch"
    function: "Leiterin Fachstelle öV und Projekte"
  - abbreviation: "GL"
    lastName: ""
    firstname: ""
    organisation: "Departement Bau und Umwelt Kt. GL"
    email: "a@b.ch"
    function: "Leiterin Fachstelle öV und Projekte"
  - abbreviation: "ZG"
    lastName: ""
    firstname: ""
    organisation: "Amt für öffentlichen Verkehr Kanton Zug"
    email: "a@b.ch"
    function: "Verkehrsplanung"
  - abbreviation: "FR"
    lastName: ""
    firstname: ""
    organisation: "DAEC/RUD FR, Service de la mobilité SMo/Amt für Mobilität MobA"
    email: "a@b.ch"
    function: "Verkehrsplanung"
  - abbreviation: "SO"
    lastName: ""
    firstname: ""
    organisation: "Amt für Verkehr und Tiefbau, Öffentlicher Verkehr"
    email: "a@b.ch"
    function: "Projektleiter Öffentlicher Verkehr"
  - abbreviation: "BS"
    lastName: ""
    firstname: ""
    organisation: "Bau- und Verkehrsdepartement des Kt. BS"
    email: "a@b.ch"
    function: "Mobilität, Mobilitätsplanung"
  - abbreviation: "BL"
    lastName: ""
    firstname: ""
    organisation: "Kanton BL, Bau- und Umweltschutzdirektion, Abteilung öffentlicher Verkehr"
    email: "a@b.ch"
    function: "Verkehrsplaner"
  - abbreviation: "SH"
    lastName: ""
    firstname: ""
    organisation: "Koordinationsstelle öffentlicher Verkehr Kanton Schaffhausen"
    email: "a@b.ch"
    function: "Verkehrsplanung"
  - abbreviation: "AR"
    lastName: ""
    firstname: ""
    organisation: "Departement Volks- und Landwirtschaft AR, Departementssekretariat"
    email: "a@b.ch"
    function: "Leiter Fachstelle öV"
  - abbreviation: "AI"
    lastName: ""
    firstname: ""
    organisation: "Amt für öffentlichen Verkehr, Volkswirtschaftsdepartement Kanton Appenzell Innerrhoden"
    email: "a@b.ch"
    function: "Verkehrsplanung"
  - abbreviation: "SG"
    lastName: ""
    firstname: ""
    organisation: "Amt für öffentlichen Verkehr, Volkswirtschaftsdepartement Kt. SG"
    email: "a@b.ch"
    function: "Verkehrsplanung"
  - abbreviation: "GR"
    lastName: ""
    firstname: ""
    organisation: "Amt für Energie und Verkehr (AEV) Kt. GR, Abteilung öffentlicher Verkehr"
    email: "a@b.ch"
    function: "Projektleiter öffentlicher Verkehr (AEV)"
  - abbreviation: "AG"
    lastName: ""
    firstname: ""
    organisation: "Kt. AG, Departement Bau, Verkehr und Umwelt, Abteilung Verkehr"
    email: "a@b.ch"
    function: "Projektleiter"
  - abbreviation: "TG"
    lastName: ""
    firstname: ""
    organisation: "Kanton Thurgau, Departement für Inneres und Volkswirtschaft (DIV), öffentlicher Verkehr"
    email: "a@b.ch"
    function: "Verkehrsplanung"
  - abbreviation: "TI"
    lastName: ""
    firstname: ""
    organisation: "Dipartimento del territorio, Sezione della mobilità, Ufficio dei trasporti pubblici"
    email: "a@b.ch"
    function: "Responsabile gestione dati TP"
  - abbreviation: "VD"
    lastName: ""
    firstname: ""
    organisation: "Canton de Vaud / DGMR"
    email: "a@b.ch"
    function: "Resp. Observatoire"
  - abbreviation: "VS"
    lastName: ""
    firstname: ""
    organisation: "Departement für Mobilität, Raumentwicklung und Umwelt / Dienststelle für Mobilität / Sektion Verkehr"
    email: "a@b.ch"
    function: "Verkehrsplanung"
  - abbreviation: "NE"
    lastName: ""
    firstname: ""
    organisation: "Service des transports NE"
    email: "a@b.ch"
    function: "Adjoint au chef de service"
  - abbreviation: "GE"
    lastName: ""
    firstname: ""
    organisation: "Département de l’environnement, des transports et de l’agriculture (DETA) Ct. GE"
    email: "a@b.ch"
    function: "Verkehrsplanung"
  - abbreviation: "JU"
    lastName: ""
    firstname: ""
    organisation: "République et Canton du Jura, Service du développement territorial, Section de la mobilité et des transports"
    email: "a@b.ch"
    function: "Ingénieur en transports"