spring:
  datasource:
    url: jdbc:postgresql://workflow-test.cdv0rjtmldns.eu-central-1.rds.amazonaws.com:5432/workflow
    username: ${DB_USER}
    password: ${DB_PWD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/v2.0

kafka:
  atlas:
    mail:
      topic: atlas.test.workflow
      groupId: atlas.kafka.workflow.groupId
    workflow:
      topic: atlas.test.workflow
      groupId: atlas.kafka.workflow.groupId
    user:
      administration:
        topic: atlas.test.user.administration
        groupId: atlas.kafka.lidi.user.administration.groupId
auth:
  audience:
    service-name: 2e8c6ce0-304d-42e1-9bce-600b3ea43aad
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n
