spring:
  datasource:
    url: jdbc:postgresql://workflow-prod.czdfgxj0x1zx.eu-central-1.rds.amazonaws.com:5432/workflow
    username: ${DB_USER}
    password: ${DB_PWD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/v2.0

kafka:
  atlas:
    mail:
      topic: atlas.workflow
      groupId: atlas.kafka.workflow.groupId
auth:
  audience:
    service-name: f3cdcb3e-1e95-4591-b664-4526d00f5d66
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n

mail:
  workflow:
    line:
      receiver: info_tuv@bav.admin.ch
      from: no-replay-atlas@sbb.ch
      mail-html-title: Antrag f체r eine neue/ge채nderte Linie 체berpr체fen.