kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  name: {{ .Chart.Name }}
spec:
  host: '{{ .Values.routeHost }}'
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: '{{ .Chart.Name }}'
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
