global:
  # Maximal CPU ie 1 for 1 Core
  cpuMax: "1"
  # Minimal CPU ie. 1m for 1 Milicore
  cpuMin: "100m"
  # Image Pull Policy
  imagePullPolicy: "Always"
  # Maximal Memory ie 1G for 1 Gigabyte
  memoryMax: "1G"
  # Minimal Memory ie 1M for 1 Megabyte
  memoryMin: "256M"
  # Pod Instances Count
  replicas: 1
  # SEPARATOR is an option to put an variation to the deploymentconfig name.
  separator: ""
  # VARIANT is an option to put an variation to the deploymentconfig name.
  variant: ""
  # Selector-Tag for Artifactory
  versiontag: ""
