kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    openshift.io/host.generated: 'true'
    clew.sbb.ch/cluster-independent-dns: 'true'
  name: '{{ .Values.product }}{{ .Values.separator }}{{ .Values.variant }}'
spec:
  host: '{{ .Values.product }}.{{ .Values.springProfilesActive }}.sbb-cloud.net'
  port:
    targetPort: '{{ .Values.port }}-tcp'
  to:
    kind: Service
    name: '{{ .Values.product }}{{ .Values.separator }}{{ .Values.variant }}'
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
