spring:
  datasource:
    url: jdbc:postgresql://line-directory-test.cdv0rjtmldns.eu-central-1.rds.amazonaws.com:5432/line_directory
    username: ${DB_USER}
    password: ${DB_PWD}
  kafka:
    atlas:
      user:
        administration:
          topic: atlas.test.user.administration
          groupId: atlas.kafka.user
auth:
  audience:
    service-name: 2e8c6ce0-304d-42e1-9bce-600b3ea43aad
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n
amazon:
  accessKey: ${AMAZON_S3_ACCESS_KEY}
  secretKey: ${AMAZON_S3_SECRET_KEY}
  region: "eu-central-1"
  bucketName: "atlas-data-export-test-dev"
  objectExpirationDays: 30