spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/line-directory?currentSchema=line_directory
    username: user
    password: pwd
    driver-class-name: org.postgresql.Driver
  application:
    name: line-directory
  jpa:
    open-in-view: false
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  jmx:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/v2.0
auth:
  audience:
    service-name: 87e6e634-6ba1-4e7a-869d-3348b4c3eafc
server:
  port: 8082
  error:
    include-message: always
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: line-directory
    version: @version@
    buildtime: @timestamp@
logging:
  level:
    root: INFO
    org.hibernate: ERROR
amazon:
  accessKey: ${AMAZON_S3_ACCESS_KEY}
  secretKey: ${AMAZON_S3_SECRET_KEY}
  region: "eu-central-1"
  bucket:
    dir: "line"
scheduler:
  export:
    zone: "Europe/Zurich"
    line:
      full-export:
        chron: "0 0 3 * * ?" #At 03:00:00am every day
      actual-export:
        chron: "0 5 3 * * ?" #At 03:05:00am every day
      future-export:
        chron: "0 10 3 * * ?" #At 03:10:00am every day