amazon:
  region: local
  bucketConfigs:
    export-files:
      accessKey: NSVCQSGo2klxYXInNuob
      secretKey: jiiCYSlwdHBkrSg8J4Htqm7Ej8ydlprZGgYFwELc
      endpoint: "http://localhost:9000"
      forcePathStyle: true
      objectExpirationDays:
    hearing-documents:
      accessKey: NSVCQSGo2klxYXInNuob
      secretKey: jiiCYSlwdHBkrSg8J4Htqm7Ej8ydlprZGgYFwELc
      endpoint: "http://localhost:9000"
      forcePathStyle: true
      objectExpirationDays: