spring:
  datasource:
    url: jdbc:postgresql://line-directory-dev.cdv0rjtmldns.eu-central-1.rds.amazonaws.com:5432/line_directory
    username: ${DB_USER}
    password: ${DB_PWD}
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{X-B3-TraceId:-} spanid=%X{X-B3-SpanId:-} message="%m"%n