publishing:
  stages:
    local:
      exportDirectory: local
      apis:
        - business-organisation-directory
        - import-service-point
        - line-directory
        - service-point-directory
        - export-service-point
        - user-administration
        - workflow
        - prm-directory
    dev:
      exportDirectory: api-dev
      apis:
        - line-directory
        - business-organisation-directory
        - service-point-directory
        - export-service-point
        - prm-directory
    test:
      exportDirectory: api-test
      apis:
        - line-directory
        - business-organisation-directory
        - service-point-directory
        - export-service-point
        - prm-directory
    int:
      exportDirectory: api-int
      apis:
        - line-directory
        - business-organisation-directory
        - service-point-directory
        - export-service-point
        - prm-directory
      excludePatterns:
        - export/batch
    prod:
      exportDirectory: api-prod
      apis:
        - line-directory
        - business-organisation-directory
        - service-point-directory
        - export-service-point
        - prm-directory
      excludePatterns:
        - timetable-hearing
        - TimetableHearing
        - export/batch