export class DataCy {
  static BACK_TO_OVERVIEW = '[data-cy=back-to-overview]';
  static ATLAS_LOGO_HOME_LINK = '[data-cy=atlas-logo-home-link]';
  static HEADER_TITLE = '[data-cy=header-title]';
  static TOTAL_RANGE = '[data-cy="total-range"]';
  static SAVE_ITEM = '[data-cy=save-item]';
  static EDIT_ITEM = '[data-cy=edit-item]';
  static DELETE_ITEM = '[data-cy=delete-item]';
  static DIALOG = '[data-cy=dialog]';
  static DIALOG_CONFIRM_BUTTON = '[data-cy=dialog-confirm-button]';
  static DIALOG_CANCEL_BUTTON = '[data-cy=dialog-cancel-button]';
  static SUBLINES_TITLE = '[data-cy=sublines-title]';
  static SLNID = '[data-cy=slnid]';
  static NEW_LINE = '[data-cy=new-line]';
  static NEW_SUBLINE = '[data-cy=new-subline]';
  static LIDI_LINES = '[data-cy="lidi-lines"]';
  static LIDI_SUBLINES = '[data-cy="lidi-sublines"]';
  static VALID_FROM = '[data-cy=validFrom]';
  static VALID_TO = '[data-cy=validTo]';
  static SWISS_LINE_NUMBER = '[data-cy=swissLineNumber]';
  static BUSINESS_ORGANISATION = '[data-cy=businessOrganisation]';
  static TYPE = '[data-cy=type]';
  static PAYMENT_TYPE = '[data-cy=paymentType]';
  static DESCRIPTION = '[data-cy=description]';
  static NUMBER = '[data-cy=number]';
  static ALTERNATIVE_NAME = '[data-cy=alternativeName]';
  static COMBINATION_NAME = '[data-cy=combinationName]';
  static LONG_NAME = '[data-cy=longName]';
  static ICON = '[data-cy=icon]';
  static COMMENT = '[data-cy=comment]';
  static MAINLINE_SLNID = '[data-cy=mainlineSlnid]';
  static SWISS_SUBLINE_NUMBER = '[data-cy=swissSublineNumber]';
  static DETAIL_SUBHEADING_ID = '[data-cy=detail-subheading-id]';
  static NEW_ITEM = '[data-cy=new-item]';
  static SWISS_TIMETABLE_FIELD_NUMBER = '[data-cy=swissTimetableFieldNumber]';

}
