kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
      deploymentconfig: {{ .Values.frontend.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        collectord.io/logs-index: '{{ .Values.common.splunkIndex }}'
        collectord.io/logs-output: splunk::prod
      labels:
        app: '{{ .Values.frontend.name }}'
        deploymentconfig: '{{ .Values.frontend.name }}'
    spec:
      containers:
        - image: "atlas.docker.bin.sbb.ch/{{ .Values.frontend.name}}:{{ .Chart.AppVersion }}"
          imagePullPolicy: '{{ .Values.common.imagePullPolicy }}'
          name: '{{ .Values.frontend.name }}'
          env:
            - name: PRODUCTION
              value: '{{ .Values.frontend.production }}'
            - name: ENVIRONMENT_LABEL
              value: '{{ .Values.frontend.environmentLabel }}'
            - name: APP_VERSION
              value: '{{ .Chart.AppVersion }}'
            - name: ATLAS_API_URL
              value: '{{ .Values.frontend.atlasApiUrl }}'
            - name: API_CLIENT_ID
              value: '{{ .Values.frontend.apiClientId }}'
            - name: API_SCOPE
              value: '{{ .Values.frontend.apiScope }}'
            - name: INSTANA_KEY
              value: '{{ .Values.frontend.instanaKey }}'
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 10
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30



