amazon:
  region: local
  bucketConfigs:
    bulk-import:
      accessKey: NSVCQSGo2klxYXInNuob
      secretKey: jiiCYSlwdHBkrSg8J4Htqm7Ej8ydlprZGgYFwELc
      endpoint: "http://localhost:9000"
      forcePathStyle: true
      objectExpirationDays: