spring:
  datasource:
    url: jdbc:postgresql://service-point-directory-dev.cdv0rjtmldns.eu-central-1.rds.amazonaws.com:5432/service_point_directory
    username: ${DB_USER}
    password: ${DB_PWD}
kafka:
  atlas:
    user:
      administration:
        topic: atlas.dev.user.administration
        groupId: atlas.kafka.spdi.user.administration.groupId
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n
