spring:
  datasource:
    url: jdbc:postgresql://service-point-directory-prod.TODO/TODO
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver

logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n
