spring:
  datasource:
    url: jdbc:postgresql://service-point-directory-prod.cdv0rjtmldns.eu-central-1.rds.amazonaws.com/service_point_directory
    username: ${DB_USER}
    password: ${DB_PWD}
kafka:
  atlas:
    user:
      administration:
        topic: atlas.prod.user.administration
        groupId: atlas.kafka.spdi.user.administration.groupId
    workflow:
      topic: atlas.prod.workflow
      groupId: atlas.kafka.workflow.groupId
auth:
  audience:
    service-name: f3cdcb3e-1e95-4591-b664-4526d00f5d66
logging:
  pattern:
    console: timestamp=%d thread=%t loglevel=%-5p class=%c appname=atlas traceid=%X{traceId} spanid=%X{spanId} message="%m"%n
