server:
  port: 8088
  error:
    include-message: always

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics

spring:
  sleuth:
    baggage:
      remote-fields: "Correlation-Id"
      correlation-fields: "Correlation-Id"
  datasource:
    url: jdbc:postgresql://localhost:5439/service-point-directory?currentSchema=service-point-directory
    username: user
    password: pwd
    driver-class-name: org.postgresql.Driver
  application:
    name: service-point-directory
  jpa:
    open-in-view: false
  jmx:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/v2.0

kafka:
  atlas:
    user:
      administration:
        topic: atlas.user.administration
        groupId: atlas.kafka.spdi.user.administration.groupId
    workflow:
      topic: atlas.workflow
      groupId: atlas.kafka.workflow.groupId

auth:
  audience:
    service-name: 87e6e634-6ba1-4e7a-869d-3348b4c3eafc

info:
  app:
    name: service-point-directory
    version: @version@
    buildtime: @timestamp@

logging:
  level:
    root: INFO
    com:
      azure:
        identity: WARN
