routeHost: 'atlas.sbb-cloud.net'
publicRoute: 'atlas.app.sbb.ch'
atlasApiUrl: 'https://atlas.api.sbb.ch:443'
splunkIndex: 'sbb_atlas_internal_prod_events'
apiClientId: 'ab56f386-eefb-4ea9-b3ad-6d8323ad4c1a'
apiScope: 'openid profile email offline_access api://f3cdcb3e-1e95-4591-b664-4526d00f5d66/.default'
clusterLoadBalancer: 'public-maggie.app.sbb.ch'
replicas: 2
